# to create a conda environment, run $ conda env create -f environment.yml
name: yield_optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.5.2
  - numpy==1.22.3
  - scikit-learn==1.0.2
  - py-xgboost==1.7.3
  - scipy==1.8.1